apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cybersyn-nodeweb
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/roxtrongo/node-web.git
    targetRevision: HEAD
    path: k8
  destination:
    server: https://kubernetes.default.svc
    namespace: cybersyn

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true